### PR TITLE
Fix ensure that setQueryData for an inactive query updates its atom s…

### PR DESCRIPTION
**Pull request by dTalion**
a test case and possible solution for the issue #39 
https://github.com/jotaijs/jotai-tanstack-query/issues/39

### CODE REVIEW

**Comment by dai-shi** [comment]
5a858a9 seems suboptimal and too hacky.

This makes me feel strongly like the current implementation isn't really align with React Query's design.
I kept saying that `jotai-tanstack-query` should be re-designed from the ground like `jotai-urql` did https://github.com/jotaijs/jotai-urql/pull/11. We can even forget about the atomsWithSomething convention (returning two atoms).
We need a new maintainer and have been looking for someone.

**Comment by dTalion** [comment]
> [5a858a9](https://github.com/jotaijs/jotai-tanstack-query/commit/5a858a9d16e39f4002f880eae37858ee0c4689ee) seems suboptimal and too hacky.
> 
> This makes me feel strongly like the current implementation isn't really align with React Query's design. I kept saying that `jotai-tanstack-query` should be re-designed from the ground like `jotai-urql` did [jotaijs/jotai-urql#11](https://github.com/jotaijs/jotai-urql/pull/11). We can even forget about the atomsWithSomething convention (returning two atoms). We need a new maintainer and have been looking for someone.

It seems a bit too hacky, but I'm not sure how to make it better with the current implementation.

**Comment by dai-shi** [comment]
I think we should really need to overhaul.
The current implementation is based on the idea that query observer is the source of truth.
It seems that this ground rule is wrong.

#17 also indicates there's some fundamental mismatch.

The original idea was to return two atoms from one util, which complicates things. If we give up `dataAtom`'s suspense behavior (which most RQ users probably don't need??), a simpler `atomWithQuery` would be possible.

Would you be interested in taking the lead of this project?

**Comment by dTalion** [comment]
The current suspense behave is not ideal, but I won't give it up tbh.

I appreciate your offer to take the lead on the project. Let me dive into it a bit deeper, and I'll get back to you with my thoughts.

**Comment by dai-shi** [comment]
That sounds great.

A bit of history: I ended up with `atomsWithQuery` returning two atoms, because I had no other ideas to use query observer like that. If we were not to give up suspense-able atom, the better abstraction would be to create two utils like `dataAtomWithQuery` and `statusAtomWithQuery` (names should be re-considered).

**Comment by kalijonn** [comment]
The new implementation fixes this issue. I've added your test from this PR in https://github.com/jotaijs/jotai-tanstack-query/pull/56

**Pull request closed without merging**
